FROM nanobox/runit

# Create directories
RUN mkdir -p /var/log/gonano

# Copy files
ADD hookit/. /opt/gonano/hookit/mod/
ADD files/. /

# Install binaries
RUN rm -rf /data/var/db/pkgin && \
    /data/bin/pkgin -y up && \
    /data/bin/pkgin -y in \
      yoke \
      postgresql94-server && \
      # postgresql94-datatypes \
      # postgresql94-fuzzystrmatch \
      # postgresql94-pgcrypto
    rm -rf /data/var/db/pkgin/cache

# Cleanup disk
RUN rm -rf \
      /var/lib/apt/lists/* \
      /tmp/* \
      /var/tmp/*

# Run runit automatically
CMD /opt/gonano/bin/nanoinit
